# Generated by Django 6.1 on 2026-08-08 08:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='portfolio/%Y/%m/%d/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер (байты)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Файл портфолио',
                'verbose_name_plural': 'Файлы портфолио',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна проживания')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('experience_projects', models.PositiveIntegerField(default=0, verbose_name='Опыт (проектов)')),
                ('languages', models.JSONField(blank=True, default=list, help_text='Формат: [{"language": "Английский", "level": "B2"}]', verbose_name='Владение языками')),
                ('key_advantages', models.JSONField(blank=True, default=list, help_text='Максимум 3 преимущества', verbose_name='Ключевые преимущества')),
                ('skills', models.JSONField(blank=True, default=list, help_text='Например: ["Холодные звонки", "SPIN", "Salesforce"]', verbose_name='Навыки и методы продаж')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на YouTube или Vimeo (до 40 секунд)', verbose_name='Видеопрезентация')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль фрилансера',
                'verbose_name_plural': 'Профили фрилансеров',
                'indexes': [models.Index(fields=['rating'], name='profiles_fr_rating_8b6d3d_idx'), models.Index(fields=['is_verified'], name='profiles_fr_is_veri_c394c1_idx'), models.Index(fields=['is_available'], name='profiles_fr_is_avai_f797c5_idx'), models.Index(fields=['country'], name='profiles_fr_country_36e3ca_idx')],
            },
        ),
    ]
