# Generated by Django 6.1 on 2026-08-10 16:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна проживания')),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='middle', max_length=20, verbose_name='Уровень')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('experience_projects', models.PositiveIntegerField(default=0, verbose_name='Опыт (проектов)')),
                ('languages', models.JSONField(blank=True, default=list, help_text='Формат: [{"language": "Английский", "level": "B2"}]', verbose_name='Владение языками')),
                ('key_advantages', models.JSONField(blank=True, default=list, help_text='Максимум 3 преимущества', verbose_name='Ключевые преимущества')),
                ('skills', models.JSONField(blank=True, default=list, help_text='Например: ["Холодные звонки", "SPIN", "Salesforce"]', verbose_name='Навыки и методы продаж')),
                ('portfolio_links', models.JSONField(blank=True, default=list, help_text='Например: ["https://linkedin.com/in/...", "https://drive.google.com/..."]', verbose_name='Ссылки на портфолио')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на YouTube или Vimeo (до 40 секунд)', verbose_name='Видеопрезентация')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='0–100%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент принятых отчётов')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Профиль фрилансера',
                'verbose_name_plural': 'Профили фрилансеров',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Например: «Кейсы B2B-продаж»', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('file', 'Файл'), ('link', 'Ссылка'), ('case', 'Кейс')], default='file', max_length=10, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio/%Y/%m/%d/', verbose_name='Файл')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер (байты)')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Элемент портфолио',
                'verbose_name_plural': 'Элементы портфолио',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
