# Generated by Django 6.1 on 2026-08-10 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='profiles.freelancerprofile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='profiles.portfolio', verbose_name='Портфолио'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['rating'], name='profiles_fr_rating_8b6d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['level'], name='profiles_fr_level_187c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['is_verified'], name='profiles_fr_is_veri_c394c1_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['is_available'], name='profiles_fr_is_avai_f797c5_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['country'], name='profiles_fr_country_36e3ca_idx'),
        ),
    ]
