# Generated by Django 6.1 on 2026-08-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Ссылка на деловое фото профиля', verbose_name='Аватар (URL)'),
        ),
    ]
