# Generated by Django 6.1 on 2026-08-23 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_avatar_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancerprofile",
            name="does_cold_calling",
            field=models.BooleanField(
                default=False,
                help_text="Cold Calling — структурированный признак для подбора",
                verbose_name="Работает с холодными звонками",
            ),
        ),
        migrations.AddField(
            model_name="freelancerprofile",
            name="does_linkedin_outreach",
            field=models.BooleanField(
                default=False,
                help_text="LinkedIn — структурированный признак для подбора",
                verbose_name="Работает с LinkedIn-аутричем",
            ),
        ),
        migrations.AddIndex(
            model_name="freelancerprofile",
            index=models.Index(
                fields=["does_cold_calling"], name="profiles_fr_does_co_bdce7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="freelancerprofile",
            index=models.Index(
                fields=["does_linkedin_outreach"], name="profiles_fr_does_li_789a73_idx"
            ),
        ),
    ]
