# Generated by Django 6.1 on 2026-08-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Директор'), ('teamlead', 'Тимлид'), ('manager', 'Менеджер'), ('freelancer', 'Фрилансер'), ('admin', 'Администратор')], default='freelancer', max_length=20, verbose_name='Роль'),
        ),
    ]
