# Generated by Django 6.1 on 2026-08-10 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_info', models.JSONField(default=dict, help_text='name, phone, email, linkedin', verbose_name='Контакты')),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('base', 'База'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Источник')),
                ('qualification_status', models.CharField(choices=[('cold', 'Холодный'), ('warm', 'Тёплый'), ('hot', 'Горячий')], default='cold', max_length=20, verbose_name='Квалификация')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('matched_hot_criteria', models.JSONField(blank=True, default=list, verbose_name='Совпавшие критерии горячего лида')),
                ('hot_handoff_at', models.DateTimeField(blank=True, null=True, verbose_name='Передан менеджеру')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_leads', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='rooms.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Было')),
                ('new_status', models.CharField(max_length=20, verbose_name='Стало')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pipeline.lead', verbose_name='Лид')),
            ],
            options={
                'verbose_name': 'История статуса лида',
                'verbose_name_plural': 'История статусов лидов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('checklist', models.JSONField(blank=True, default=list, help_text='[{"text": "...", "done": false}]', verbose_name='Чеклист')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('ready_for_review', 'На проверке'), ('approved', 'Утверждена'), ('rejected', 'Отклонена'), ('closed', 'Закрыта')], default='new', max_length=32, verbose_name='Статус')),
                ('task_type', models.CharField(choices=[('work', 'Рабочая'), ('manager_handoff', 'Горячий лид → менеджер'), ('onboarding', 'Онбординг')], default='work', max_length=32, verbose_name='Тип задачи')),
                ('report_required', models.BooleanField(default=True, verbose_name='Обязателен отчёт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_tasks', to='pipeline.lead', verbose_name='Связанный лид')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rooms.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_text', models.TextField(verbose_name='Текст отчёта')),
                ('attachment', models.FileField(upload_to='reports/%Y/%m/%d/', verbose_name='Вложение (скриншот)')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='Комментарий проверяющего')),
                ('review_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус проверки')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pipeline.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
    ]
