# Generated by Django 6.1 on 2026-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Закрыта"
            ),
        ),
    ]
