# Generated by Django 6.1 on 2026-09-01 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_task_closed_at'),
        ('rooms', '0009_roomchatmessage_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerAccrual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (USD)')),
                ('title', models.CharField(max_length=255, verbose_name='Основание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Начислено')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to=settings.AUTH_USER_MODEL, verbose_name='Фрилансер')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_accruals', to='rooms.project', verbose_name='Проект')),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accrual', to='pipeline.report', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Начисление фрилансеру',
                'verbose_name_plural': 'Начисления фрилансерам',
                'ordering': ['-created_at'],
            },
        ),
    ]
