# Generated by Django 6.1 on 2026-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_freelanceraccrual'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='discovery_checks',
            field=models.JSONField(blank=True, default=dict, help_text='Факты разговора (BANT + next step); не двигает колонку Cold/Warm/Hot.', verbose_name='Чеклист квалификации'),
        ),
    ]
