# Generated by Django 6.1 on 2026-08-10 20:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('project_type', models.CharField(choices=[('base', 'По базе'), ('linkedin_outreach', 'Аутрич LinkedIn')], default='base', max_length=32, verbose_name='Тип продаж')),
                ('seller_level', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='middle', max_length=20, verbose_name='Уровень продавцов')),
                ('tariff_plan', models.CharField(default='launch', max_length=50, verbose_name='Тариф')),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='offer, audience, hot_criteria, utp, notes', verbose_name='Вводные по шаблону')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бюджет')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата старта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('launched', 'Запущен'), ('staffing', 'Подбор команды'), ('active', 'Активен'), ('on_hold', 'Приостановлен'), ('completed', 'Завершён'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('kpi_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Целевой KPI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Директор')),
                ('teamlead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL, verbose_name='Тимлид')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_enabled', models.BooleanField(default=False, verbose_name='Чат включён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rooms.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='RoomDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='rooms/documents/%Y/%m/%d/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rooms.room', verbose_name='Комната')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_room_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ комнаты',
                'verbose_name_plural': 'Документы комнат',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_room', models.CharField(choices=[('director', 'Директор'), ('teamlead', 'Тимлид'), ('freelancer', 'Фрилансер')], max_length=20, verbose_name='Роль в комнате')),
                ('ready_status', models.CharField(choices=[('pending', 'Ожидает'), ('ready', 'Готов к работе'), ('declined', 'Отказался')], default='pending', max_length=20, verbose_name='Готовность')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rooms.room', verbose_name='Комната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник комнаты',
                'verbose_name_plural': 'Участники комнат',
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_room_member')],
            },
        ),
    ]
