# Generated by Django 6.1 on 2026-08-11 05:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('project_launched', 'Проект запущен'), ('member_added', 'Участник добавлен'), ('member_removed', 'Участник удалён'), ('teamlead_assigned', 'Тимлид назначен'), ('document_uploaded', 'Документ загружен'), ('task_created', 'Задача создана'), ('lead_created', 'Лид создан'), ('ready', 'Готовность'), ('other', 'Другое')], default='other', max_length=40, verbose_name='Тип')),
                ('message', models.CharField(max_length=500, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_activities', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='rooms.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Событие комнаты',
                'verbose_name_plural': 'События комнат',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamleadInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принято')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_teamlead_invites', to=settings.AUTH_USER_MODEL, verbose_name='Принял')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teamlead_invites', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamlead_invites', to='rooms.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Приглашение тимлида',
                'verbose_name_plural': 'Приглашения тимлидов',
                'ordering': ['-created_at'],
            },
        ),
    ]
