# Generated by Django 6.1 on 2026-08-23 17:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_activity_and_teamlead_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="roommember",
            name="role_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Какую бизнес-функцию закрывает участник (например seller). Не заменяет role_in_room: тот отвечает за права в комнате.",
                max_length=64,
                verbose_name="Ключ закрываемой функции",
            ),
        ),
        migrations.CreateModel(
            name="RoomFunctionSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_key",
                    models.CharField(
                        help_text="Стабильный ключ бизнес-функции, например seller. Каталог ролей — отдельный этап, поэтому справочник в БД не заводим.",
                        max_length=64,
                        verbose_name="Ключ функции",
                    ),
                ),
                (
                    "slot_index",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Различает одинаковые роли внутри комнаты: 1, 2, 3…",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Номер слота",
                    ),
                ),
                (
                    "required_level",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("middle", "Middle"),
                            ("senior", "Senior"),
                        ],
                        default="middle",
                        max_length=20,
                        verbose_name="Требуемый грейд",
                    ),
                ),
                (
                    "required_channel",
                    models.CharField(
                        choices=[
                            ("any", "Любой канал"),
                            ("cold_calling", "Холодные звонки"),
                            ("linkedin", "LinkedIn"),
                        ],
                        default="any",
                        max_length=20,
                        verbose_name="Требуемый канал",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False — слот закрыт (отменён) и в подборе не участвует",
                        verbose_name="Слот активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="function_slots",
                        to="rooms.room",
                        verbose_name="Комната",
                    ),
                ),
            ],
            options={
                "verbose_name": "Функциональный слот",
                "verbose_name_plural": "Функциональные слоты",
                "ordering": ["role_key", "slot_index"],
            },
        ),
        migrations.AddField(
            model_name="roommember",
            name="function_slot",
            field=models.OneToOneField(
                blank=True,
                help_text="Единственный источник истины «кто занимает слот»",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member",
                to="rooms.roomfunctionslot",
                verbose_name="Функциональный слот",
            ),
        ),
        migrations.CreateModel(
            name="RoomSlotCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("shown", "Показан"),
                            ("assigned", "Назначен"),
                            ("skipped", "Пропущен"),
                            ("declined", "Отказался"),
                        ],
                        default="shown",
                        max_length=20,
                        verbose_name="Результат",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_candidate_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто изменил",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_candidacies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кандидат",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="rooms.roomfunctionslot",
                        verbose_name="Слот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кандидат на слот",
                "verbose_name_plural": "Кандидаты на слоты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="roomfunctionslot",
            constraint=models.UniqueConstraint(
                fields=("room", "role_key", "slot_index"),
                name="unique_room_function_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomslotcandidate",
            constraint=models.UniqueConstraint(
                fields=("slot", "candidate"), name="unique_slot_candidate"
            ),
        ),
    ]
