# Generated by Django 6.1 on 2026-08-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_roommember_role_key_roomfunctionslot_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="roomfunctionslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot_index__gte", 1)),
                name="room_function_slot_index_min_1",
            ),
        ),
    ]
