# Generated by Django 6.1 on 2026-08-24 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_roomfunctionslot_room_function_slot_index_min_1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Отправлено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="rooms.room",
                        verbose_name="Комната",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение чата",
                "verbose_name_plural": "Сообщения чата",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "created_at"], name="room_chat_room_created_idx"
                    )
                ],
            },
        ),
    ]
