# Generated by Django 6.1 on 2026-08-24 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_enable_chat_for_existing_rooms"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionalRoleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_key",
                    models.CharField(
                        choices=[
                            ("teamlead", "Тимлид проекта"),
                            ("seller_middle", "Сейлер Middle"),
                            ("seller_senior", "Сейлер Senior"),
                            ("linkedin_leadgen", "Лидген LinkedIn"),
                            ("database_assistant", "Ассистент базы"),
                        ],
                        help_text="Структурный ключ из каталога. После создания не меняется.",
                        max_length=64,
                        unique=True,
                        verbose_name="Ключ функции",
                    ),
                ),
                (
                    "monthly_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость, ₽/мес",
                    ),
                ),
                (
                    "monthly_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Часов в месяц"
                    ),
                ),
                (
                    "productivity_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Текстовое описание строки, например «60 звонков / день».",
                        max_length=255,
                        verbose_name="Продуктивность",
                    ),
                ),
                (
                    "hot_leads_per_month",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hot-лидов в месяц"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Бизнес-параметры функции",
                "verbose_name_plural": "Бизнес-параметры функций",
                "ordering": ["role_key"],
            },
        ),
    ]
