# Generated by Django 6.1 on 2026-09-01 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_enable_chat_for_existing_rooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchatmessage',
            name='channel',
            field=models.CharField(choices=[('team', 'Команда'), ('director_teamlead', 'Директор — тимлид')], default='team', max_length=32, verbose_name='Канал'),
        ),
        migrations.AddIndex(
            model_name='roomchatmessage',
            index=models.Index(fields=['room', 'channel', 'created_at'], name='room_chat_chan_created_idx'),
        ),
    ]
