# Generated by Django 5.1.1 on 2026-09-04 12:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_roomchatmessage_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReadCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('team', 'Команда'), ('director_teamlead', 'Директор — тимлид')], max_length=32)),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее прочтение')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_cursors', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_cursors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Курсор прочтения чата',
                'verbose_name_plural': 'Курсоры прочтения чата',
                'constraints': [models.UniqueConstraint(fields=('user', 'room', 'channel'), name='unique_chat_read_cursor')],
            },
        ),
    ]
