# Generated by Django 6.1 on 2026-09-05 12:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0009_roomchatmessage_channel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="roommember",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="False — членство в архиве: человек вышел из проекта, но строка сохраняется вместе со своей историей. Удалять участника ради «чистого слота» нельзя.",
                verbose_name="Участие активно",
            ),
        ),
        migrations.AddField(
            model_name="roommember",
            name="left_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Момент архивации членства; у активного участника пусто.",
                null=True,
                verbose_name="Вышел из проекта",
            ),
        ),
        migrations.CreateModel(
            name="FreelancerTermination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(verbose_name="Причина")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("notice_sent", "Уведомление отправлено"),
                            ("appeal_pending", "Оспаривается"),
                            ("completed", "Расторгнуто"),
                            ("revoked", "Отозвано"),
                        ],
                        default="notice_sent",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "initiated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Не auto_now_add: от этого момента отсчитывается срок ответа, и он должен оставаться воспроизводимым значением.",
                        verbose_name="Уведомление отправлено",
                    ),
                ),
                (
                    "deadline_at",
                    models.DateTimeField(
                        help_text="Момент, после которого молчание считается уходом.",
                        verbose_name="Ответ до",
                    ),
                ),
                (
                    "appealed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Оспорено"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Расторгнуто"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отозвано"
                    ),
                ),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminations_as_freelancer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Фрилансер",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminations_initiated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инициатор",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ссылка на строку членства. SET_NULL: удаление участника при замене на слоте не должно уносить историю расторжения.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminations",
                        to="rooms.roommember",
                        verbose_name="Членство",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminations",
                        to="rooms.room",
                        verbose_name="Комната",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расторжение с фрилансером",
                "verbose_name_plural": "Расторжения с фрилансерами",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="TerminationMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Отправлено"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="termination_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="rooms.freelancertermination",
                        verbose_name="Кейс расторжения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение расторжения",
                "verbose_name_plural": "Сообщения расторжения",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="freelancertermination",
            index=models.Index(
                fields=["status", "deadline_at"], name="room_termination_due_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="freelancertermination",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("notice_sent", "appeal_pending"))),
                fields=("room", "freelancer"),
                name="unique_open_freelancer_termination",
            ),
        ),
    ]
