# Generated by Django 6.1 on 2026-09-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0010_roommember_is_active_roommember_left_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancertermination",
            name="appeal_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Текст протеста. Пишется один раз, вместе с переходом в «Оспаривается», и после этого не редактируется: письмо поддержке уже ушло с этой формулировкой.",
                verbose_name="С чем не согласен фрилансер",
            ),
        ),
    ]
