# Generated by Django 5.1.1 on 2026-09-05 19:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_chatreadcursor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatreadcursor',
            options={'ordering': ['-last_read_at'], 'verbose_name': 'Курсор прочтения чата', 'verbose_name_plural': 'Курсоры прочтения чата'},
        ),
        migrations.RemoveConstraint(
            model_name='chatreadcursor',
            name='unique_chat_read_cursor',
        ),
        migrations.AlterField(
            model_name='chatreadcursor',
            name='channel',
            field=models.CharField(choices=[('team', 'Команда'), ('director_teamlead', 'Директор ↔ Тимлид')], max_length=32, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='chatreadcursor',
            name='last_read_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее прочитанное время'),
        ),
        migrations.AlterField(
            model_name='chatreadcursor',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_cursors', to='rooms.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='chatreadcursor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_cursors', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='chatreadcursor',
            unique_together={('user', 'room', 'channel')},
        ),
    ]
