# Generated by Django 5.1.1 on 2026-09-05 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_chatreadcursor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatreadcursor',
            options={'verbose_name': 'Курсор прочтения чата', 'verbose_name_plural': 'Курсоры прочтения чата'},
        ),
        migrations.AlterUniqueTogether(
            name='chatreadcursor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chatreadcursor',
            name='channel',
            field=models.CharField(choices=[('team', 'Команда'), ('director_teamlead', 'Директор — тимлид')], max_length=32),
        ),
        migrations.AlterField(
            model_name='chatreadcursor',
            name='last_read_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее прочтение'),
        ),
        migrations.AlterField(
            model_name='chatreadcursor',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_cursors', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='chatreadcursor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_cursors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatreadcursor',
            constraint=models.UniqueConstraint(fields=('user', 'room', 'channel'), name='unique_chat_read_cursor'),
        ),
    ]
