# Generated by Django 5.1.1 on 2026-09-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_roommember_is_active_roommember_left_at_and_more'),
        ('rooms', '0012_alter_chatreadcursor_options_and_more'),
    ]

    operations = [
    ]
